<?php

/**
 * Default system settings.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    'app-name'             => 'Library',
    'app-logo'             => '',
    'app-name-header'      => true,
    'app-editor'           => 'wysiwyg',
    'app-color'            => '#214E72',
    'app-color-light'      => 'rgba(32,110,167,0.15)',
    'bookshelf-color'      => '#214E72',
    'book-color'           => '#214E72',
    'chapter-color'        => '#214E72',
    'page-color'           => '#214E72',
    'page-draft-color'     => '#214E72',
    'app-custom-head'      => false,
    'registration-enabled' => false,

];
